---

- name: Ensure all packages to run Apache2 are present
  ansible.builtin.apt:
    pkg:
    - apache2
    - curl

- name: Enable apache2 service and make sure it's started
  ansible.builtin.systemd:
    name:  apache2
    enabled: yes
    masked: no
    state: started

- name: Change apache2 to listen on port 81 instead of 80
  ansible.builtin.lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    line: Listen 81

#- name: Download dokuwiki and install/configure it
#  block:
#    - name: Check if directory /var/www/dokuwiki exists
#      stat:
#        path: "/var/www/dokuwiki"
#      register: dokuwiki
#
#    - name: Download and extract dokuwiki targz
#      unarchive:
#        src: files/tmp/dokuwiki-a6b3119b5d16cfdee29a855275c5759f.tgz
#        dest: /var/www
#      when: not dokuwiki.stat.exists

#- name: Download 

...
